### ISSUE TITLE
Apps not appearing in app selection list when adding channel

### ISSUE THREAD

**Issue by Chibi-Usa** [KaruzoHikari/Wii-Phone#1]
i have tried this on my Moto G play (2021) and my samsung galaxy a10

the apps that cannot be found are google chrome, google messages (usually the default messages app for sms on android devices), google drive, and some apps that were installed by default on my device, not going to list because its a lot

Edit: Spelling

**Comment by Chibi-Usa** [comment]
both are running android 10

**Comment by wiggleforlife** [comment]
Same issue, Pixel 5 on Android 11

**Comment by KaruzoHikari** [comment]
Hey there!

I've just pushed Wii Phone v1.2 to the Play Store, with 3 main changes:
 - Fixed app finder excluding system pre-installed apps (this bug)
 - Adapted the menus so they fit any height / width (no more black bars, hopefully)
 - Allow users to leave the animation editor without saving changes

It should be available soon, as soon as Google reviews it.
Thanks for the report, and feel free let me know if it's still not working!

**Comment by Chibi-Usa** [comment]
The main issue is solved

👍
