### ISSUE TITLE
App crashing after warning-health & safety

### ISSUE THREAD

**Issue by MurasakinoRamen** [KaruzoHikari/Wii-Phone#10]
Everytime I open the app the default Unity logo will appear for a bit then it'll bring me to the "Warning-health & Safety" page. It'll tell you that if you have any crashes to go to this github page and submit an issue. Flashing text underneath will tell you to "Press (A) to start" and which you would normally tap the screen. Once doing so my app will go through a downloading phase. Once complete, it'll just crash and do nothing. If I have anything running, it also crashes that. I've went into the settings and gave it storage permissions because i thought that might've been the reason it was working.
My phone: Samsung a10e

**Comment by MurasakinoRamen** [comment]
I really love the entire concept behind this app, and any help would he appreciated. Thank you for your time.

**Comment by MurasakinoRamen** [comment]
I have downloaded both versions. The launcher does the same thing but works a little better. It honestly feels like it's loading animations, and even made the Wii sound effect like it was actually going to boot up. Unfortunately, it did not.

**Comment by KaruzoHikari** [comment]
Hey there! Sorry for the -very- late reply, I wasn't able to work on a new update until now.
The issue has been identified (hopefully), and fixed in the new update (v2.4)!
Please reopen the issue if it's not fully fixed.
