### ISSUE TITLE
New update makes icons disappear automatically

### ISSUE THREAD

**Issue by GithubUser559** [KaruzoHikari/Wii-Phone#102]
Bruhh.Please test More the updates @KaruzoHikari  My Wii Menú Is ruines.

**Comment by KaruzoHikari** [comment]
You're gonna have to give me some more details, this issue shouldn't be happening anymore in v5.2.2 (from last night)
- Are you in v5.2.2?
- Which version did you update from?
- Does it happen only with old icons or with new ones too?
- Does it happen only with animations you had already downloaded, or with newly downloaded animations too?

**Comment by GithubUser559** [comment]
1. 5.2.1 LOL I didn't know there was a new update, you must notify it in the Play store version. 2. 5.2  3.With all 4. with all

**Comment by KaruzoHikari** [comment]
Yeah I didn't trigger the update popup because I won't be able to build the PC versions until tomorrow, sorry about that.
Try with v5.2.2, setup a new channel (or set the animations again in the current ones) and let me know if it works

**Comment by GithubUser559** [comment]
> Yeah I didn't trigger the update popup because I won't be able to build the PC versions until tomorrow, sorry about that. Try with v5.2.2, setup a new channel (or set the animations again in the current ones) and let me know if it works

Please fix the MP4 bug in a Update. Thank you for attending me. Very few developers hear to their users.

**Comment by GithubUser559** [comment]
Works

**Comment by GithubUser559** [comment]
And fixed the Gif Error in Channel bordes (Problems of v5.2.1)
