### ISSUE TITLE
Mac version does not launch

### ISSUE THREAD

**Issue by starptr** [KaruzoHikari/Wii-Phone#113]
Not sure what is expected, but opening the app fails with "can't be opened" on an arm Mac.

**Comment by KaruzoHikari** [comment]
Hey there! Unfortunately I don't have a Mac myself to test it, but another user shared these steps in the Discord server to fix some issues he had. You can try it with the latest version and let me know if it helps!
![image](https://github.com/user-attachments/assets/b3365d48-05b5-4ca8-81fc-8ff3c53402c4)

**Comment by starptr** [comment]
Thanks it works! This is a neat app!

(I believe this issue can be fixed if you don't distribute the mac app inside of a zip file, as zip files don't preserve the execute flag. The only file I needed to run `chmod a+x` on is `'RevoLauncher_v5.2.2_Mac.app/Contents/MacOS/Revo Launcher'`.)
