### ISSUE TITLE
[Feature Request] Change Disc Channel App to launch Dolphin MMJR

### ISSUE THREAD

**Issue by Woganog** [KaruzoHikari/Wii-Phone#15]
This would be very useful!

Please add it in the settings.

**Comment by KaruzoHikari** [comment]
Hey there!
Unfortunately I believe that redirecting users to the official Dolphin project on Play Store will be best, as most people won't know how to use MMJR (or even what it is).

However, you can replace the disc channel yourself! Just use 2 fingers to move/delete the Disc Channel, then hold the empty space to create a new channel (with the Disc animations) leading to MMJR.
Let me know if you find any trouble.
