### ISSUE TITLE
Skipped Channels

### ISSUE THREAD

**Issue by 1risET** [KaruzoHikari/Wii-Phone#17]
When switching between channels through the arrows on the left and right, for some reason on my phone (pixel 6, has 5 rows instead of 4) skips the bottom two and loops back around to the disc channel.

Plus, when selecting one of the two apps on the bottom row, going going right on my spotify app will bring me to the disc channel, and when on my wii vault app, clicking left brings me back to spotify? 

https://cdn.discordapp.com/attachments/927648250167697418/954599252171046912/screen-20220318-2334002.mp4 (recording, pixel 6)

**Comment by KaruzoHikari** [comment]
Fixed in v2.4! Please reopen the issue if it's not fully fixed.
