### ISSUE TITLE
All Apps

### ISSUE THREAD

**Issue by RestartB** [KaruzoHikari/Wii-Phone#19]
Any way to have a channel or button that gives you a list of all apps? Thank you

**Comment by KaruzoHikari** [comment]
Heya!
Not at the moment, but you're completely right that it's a must. I'll make sure to add it in a future update.

**Comment by KaruzoHikari** [comment]
Forgot to close this - As of Wii Phone v3.0, holding the Wii button will open your whole list of apps, to launch them immediately
