### ISSUE TITLE
App doesn't reach the top border of the screen

### ISSUE THREAD

**Issue by wiggleforlife** [KaruzoHikari/Wii-Phone#2]
Updated to 1.2, helped with the bottom, that's a big black bar gone. However, on my Pixel 5 there's still a black bar at the top because of the hole punch. Other apps, such as YT, Spotify, Discord, etc, don't have this. Is there a way to remove it and extend the background on devices like this?

**Comment by Puffball64** [comment]
Do you have "legacy display" on?

**Comment by wiggleforlife** [comment]
> Do you have "legacy display" on?

I believe you are misunderstanding. The top is chopped off, not the top and the bottom. Turning on legacy display chops off both, turning it off still has the top chopped off.

**Comment by GlichtingNo** [comment]
I think its pretty good that it does not reach the top of the screen because of the bar on the top which shows notifications and stuff like this. It would look weird if they overlap because both are white. I have a Samsung S20 so i dont know if google phones have this bar too.

**Comment by KaruzoHikari** [comment]
I've been checking around the Unity API but in theory the app should already be extending itself past the notch.
I've done testing in emulated devices and it's also extending in there, and other notch devices seem to be working fine as well.

So I'm not sure what I can do to fix right now, I'll close the issue. If I find a way to improve notch handling, I'll add a preference to the Wii Settings in the future. Sorry about that.
