### ISSUE TITLE
the link to download the launcher is not working

### ISSUE THREAD

**Issue by Kaua2009** [KaruzoHikari/Wii-Phone#26]
![100 Sem Título_20220806134213.png](https://user-images.githubusercontent.com/87392738/183258156-5d7c0b42-46b5-4fcf-b8c9-5efc9555a690.png)
note: the image was in Portuguese and I had to edit it to translate the message because I don't know how to change the language of the "internet" application

**Comment by KaruzoHikari** [comment]
I believe the web was down at the time, should be fixed now.
