### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Chibi-Usa** [KaruzoHikari/Wii-Phone#3]
Add the internet channel, because webbrowsers,

 add support for .mp3,  cant seem to add them for banners

in the launcher settings, add phone settings that launches the settings app on android

allow for non 24h times at the bottom

**Comment by Champizoid** [comment]
A feature to add more pages and or apps

**Comment by KaruzoHikari** [comment]
Hey there! Sorry for the *really*  late reply, uni is keeping me fairly busy.

As for @Chibi-Usa:
1. The Internet channel can be recreated just as well as the other default animations (they all were done through the in-app animation creator). I ain't no artist tho - I already had a lot of trouble animating those, so I don't think I can't pull that one out
2. Indeed, right now only .wav works, but .mp3 is the most common format, so I should look that up
3. Yup! Will be available in the next release
4. Sounds good, I'll add am/pm formats to the time as well

For @Champizoid:
Sure thing! I'll add an option in the launcher settings to add more pages

**Comment by Champizoid** [comment]
Thanks again

**Comment by KaruzoHikari** [comment]
Wii Phone v2.0 has been released!
With it, all the features I promised to add have been added, so I'll close the issue.
Thanks for your suggestions!
