### ISSUE TITLE
[Bug] Launcher not installing since the package names conflict

### ISSUE THREAD

**Issue by garridk** [KaruzoHikari/Wii-Phone#31]
Every time I try to install the launcher it says "App not installed." Is there anything I can do to fix this?

**Comment by DatGamerYoloYT** [comment]
do you have the app store version still installed? uninstall that first then try again.

**Comment by KaruzoHikari** [comment]
Hey there!
Indeed, that's one of the issues with the launcher version. It's using the same package name (aka, the internal app name Android uses to differentiate apps) as the Play Store version, so it won't let you install it.
I'm currently planning a way to migrate your data to a new version (which will use a different package name), so it'll get fixed.

**Comment by KaruzoHikari** [comment]
Fixed in Wii Phone v3.2 with the introduction of the upgrade process!
