### ISSUE TITLE
Launcher crashes after pinning more than 30 apps on the screen

### ISSUE THREAD

**Issue by Thelaptopmann** [KaruzoHikari/Wii-Phone#37]
The app works for a few seconds, then crashes, I want to put as many apps as I like without it crashing, sincerely, The laptop man.

**Comment by KaruzoHikari** [comment]
Hey there!
I'm investigating this under #23, so I'll close this.

On the other hand, would you mind joining the Discord server and pinging me there?
I'm trying to pinpoint the issue, and I'd love to have some people to help with it. I'm having a hard trouble getting the app to crash on my phone haha

**Comment by Thelaptopmann** [comment]
I don't have discord
