### ISSUE TITLE
[Bug] Issue when doing a Restart/Power off

### ISSUE THREAD

**Issue by Champizoid** [KaruzoHikari/Wii-Phone#4]
Whenever I reset or turn off my phone the app removes the apps I put including the apps already there.

**Comment by Puffball64** [comment]
Tried recreating it. I couldn't. However from the little knowledge I have you can uninstall and reinstall to fix it.

**Comment by Champizoid** [comment]
That's what I have been doing but waiting it out for a few minutes was a
better alternative than uninstall and reinstall. Thank you for the reply.

**Comment by KaruzoHikari** [comment]
Try again with the new version of Wii Phone (v2.0), the way files are handled have been changed, which should improve the crashes.

**Comment by Champizoid** [comment]
Alright I'll see

**Comment by KaruzoHikari** [comment]
So, was it fixed?

**Comment by KaruzoHikari** [comment]
Fixed in v2.4! Please reopen the issue if it's not fully fixed.
