### ISSUE TITLE
[Feature Request] - a way to view all apps on the homescreen

### ISSUE THREAD

**Issue by diorcula** [KaruzoHikari/Wii-Phone#45]
i love the app,
no crashes whatsoever so also have it as my current launcher.

one thing i do miss is a way to view all my apps, as i am using the launcher as a way to keep my homescreen clean, i do need a way to view all my apps instead of adding them all to different pages.

**Comment by 111ebobo** [comment]
> i love the app,
> no crashes whatsoever so also have it as my current launcher.
> 
> one thing i do miss is a way to view all my apps, as i am using the launcher as a way to keep my homescreen clean, i do need a way to view all my apps instead of adding them all to different pages.

Hold Wii button
