### ISSUE TITLE
Wii U

### ISSUE THREAD

**Issue by DylanAaro** [KaruzoHikari/Wii-Phone#56]
Udjdj

**Comment by DylanAaro** [comment]
![de4bbb9e-1e0c-4b5a-a27f-062a79175df0.jpeg](https://github.com/KaruzoHikari/Wii-Phone/assets/139168006/c8fe1ab4-322d-4be7-b459-9cac6e1d7da7)

**Comment by gdandsm64fan123** [comment]
Wtf is this, CLOSE THIS NOW
