### ISSUE TITLE
Unity Splash Screen, Wii Safety Screen and Settings app through Wii Settings Menu

### ISSUE THREAD

**Issue by GlichtingNo** [KaruzoHikari/Wii-Phone#6]
I love this app so much and I already use it as my Laucher most of the time. There are only 3 things I wish you will change in the next update: 1. The main thing i hope you will change is The Unity Splash screen. Could you just delete it (prefered option) or customize it so it is the "Wii Safety Warning screen" it would be amazing if this was possible because its pretty annoying when using the app as launcher. 2. Could you make a option to disable the "Wii Safety Warning screen" It is also a bit annoying when using the app as launcher. 3. It would be a pretty cool feature if you could add a button in the Wii Settings menu that opens the Phones settings app. If you could change these 3 things the app would be perfect. You created something I wanted for a very long time Thank you so much <3

**Comment by KaruzoHikari** [comment]
Hey there! Sorry for the late reply, uni is keeping me really busy.

1. Unfortunately I can't remove the Unity splash screen, nor change it to be the warning screen. This is the main limitation of the free license of Unity - the only way to remove it is paying for Unity Plus / Unity Pro, and I deff can't afford it (I don't make any kind of revenue with this app - no ads, no microtransactions, no shared data! Just a hobby project :)
2. Indeed! That's on me, I have an option on the Unity Editor to disable it, but forgot to add an option to it in the Wii menu. Will be available in the next release.
3. Doable as well! I'll just add a button in the Preferences to open your phone settings.

Thanks for sticking around and using my app! I wasn't expecting people to *actually*  use it as a launcher, really cool to hear that

**Comment by KaruzoHikari** [comment]
Wii Phone v2.0 has been released!
With that, both features I promised to add have been added, so I'll close the issue.
Thanks for your suggestions!
