### ISSUE TITLE
For This reason accept My theme

### ISSUE THREAD

**Issue by GithubUser559** [KaruzoHikari/Wii-Phone#87]
I changed the name of my theme from Wii U Evolution to Wii U Revolution. When I saved it wouldn't let me quit. I had to restart the application. and my theme disappeared,Fortunately I posted it on the Content Hub and it is in moderation. @KaruzoHikari Please talk to the moderators to publish and recover my theme, My theme was turning out better than a Wii U theme.

**Comment by KaruzoHikari** [comment]
Hi, are you in the Discord? if so please contact me in there, it might be easier to handle.

**Comment by GithubUser559** [comment]
> Hi, are you in the Discord? if so please contact me in there, it might be easier to handle.

No,But Please talk With the moderators

**Comment by GithubUser559** [comment]
> Hi, are you in the Discord? if so please contact me in there, it might be easier to handle.

The name of my theme in moderation Is Wii U Evolution

**Comment by GithubUser559** [comment]
> Hi, are you in the Discord? if so please contact me in there, it might be easier to handle.

And has a Lot of Green And Live wallpapers Based on the Kzumi Wii U Theme.

**Comment by KaruzoHikari** [comment]
Sure, I can look into approving it at least so you can recover it.
However, if you can't join the Discord, then it'd be good if you could tell me here what you were doing when the error happened, in order to identify the issue.
Did you just try to rename a theme and the saving issue occurred? Or did you import any new assets, change any text... Please try to remember, thanks!

**Comment by GithubUser559** [comment]
> Sure, I can look into approving it at least so you can recover it. However, if you can't join the Discord, then it'd be good if you could tell me here what you were doing when the error happened, in order to identify the issue. Did you just try to rename a theme and the saving issue occurred? Or did you import any new assets, change any text... Please try to remember, thanks!

I Changed The Warning screen finally For rentando My theme from the Kzumi Theme AND Changed The name to Wii U Revolution.When i save,The application was bugged and wouldn't let me exit the editor,I had to restart the application and lose my theme But The Anterior versión of my theme I Publish In Content Hub And Is in moderation

**Comment by KaruzoHikari** [comment]
I've approved the theme so you can make the needed changes. But if this theme branches out from Hzumi:k's, make sure to credit them appropriately when sending it again for review.

Four quick questions:
- Did you do this in the latest version (v5.1)?
- Were you in Android or PC?
- If you were on Android, were you using the Android native file browser, or the built-in one? (This one is enabled by clicking on "Fix file pickers", but it's disabled by default.
- So the only 2 changes you did is changing the warning screen texture + changing the theme's name?

**Comment by GithubUser559** [comment]
> I've approved the theme so you can make the needed changes. But if this theme branches out from Hzumi:k's, make sure to credit them appropriately when sending it again for review.
> 
> Four quick questions:
> 
> * Did you do this in the latest version (v5.1)?
> * Were you in Android or PC?
> * If you were on Android, were you using the Android native file browser, or the built-in one? (This one is enabled by clicking on "Fix file pickers", but it's disabled by default.
> * So the only 2 changes you did is changing the warning screen texture + changing the theme's name?

1.Yes, My versión Is 5.1.             2.Android           3.Native file browser.       4.No,I Made  a Lot of Changes,But i dont Made the Warning screen  Because I was making a new versión  to change the name from Wii u Evolution to Wii U Revolution and Change The Warning screen

**Comment by GithubUser559** [comment]
> Sure, I can look into approving it at least so you can recover it. However, if you can't join the Discord, then it'd be good if you could tell me here what you were doing when the error happened, in order to identify the issue. Did you just try to rename a theme and the saving issue occurred? Or did you import any new assets, change any text... Please try to remember, thanks!

Thanks

**Comment by GithubUser559** [comment]
I give the crédits in comments

**Comment by KaruzoHikari** [comment]
The credit should at least be done in the theme's description, not in the comments. Let me know if you've already re-downloaded the theme so I can delete it from the Hub, until you send to review the final fixed version.

**Comment by GithubUser559** [comment]
Yes i re download my theme.Im working in a new versión

**Comment by GithubUser559** [comment]
I Send a Update for the theme.

**Comment by GithubUser559** [comment]
> The credit should at least be done in the theme's description, not in the comments. Let me know if you've already re-downloaded the theme so I can delete it from the Hub, until you send to review the final fixed version.

Please Denie all My Themes in Moderation.It is to give the most revolutionary Wii Phone theme Taking advantage of all the tools and the .gif format of the Popular launchers creator. @KaruzoHikari I have already finished the Defenitive versions  Of Wii U Revolution Blue White Green Black.

**Comment by GithubUser559** [comment]
Accept The new versión. I Delete the old ones quickly because they were outdated and missed many features

**Comment by GithubUser559** [comment]
@KaruzoHikari

**Comment by GithubUser559** [comment]
The new update improves the resolution AND Fixing things that new versions have been breaking. Also color improvement Custon banners And more
