### ISSUE TITLE
[Feature Request] More channels

### ISSUE THREAD

**Issue by upintheairsheep** [KaruzoHikari/Wii-Phone#9]
Internet channel is Google chrome

Netflix, Amazon prime, Hulu, Crunchyroll, and watchever apps

Food delivery channel is grub hub or Uber eats

**Comment by IceFireDude** [comment]
You yourself can also put channels in my holding the space with 2 fingers :)

**Comment by DojinKing224** [comment]
Oh, and Wii no Ma is some virtual pet game

**Comment by DojinKing224** [comment]
Maybe tv no tomo could be some kinda tv app

**Comment by upintheairsheep** [comment]
And disc channel should be a dvd app

**Comment by DojinKing224** [comment]
You will soon get a Mediafire link to my WIP channels. Enjoy when I dump it in the link.

**Comment by DojinKing224** [comment]
Some can be gotten with the 3.0 update.

**Comment by KaruzoHikari** [comment]
The Animations Hub was released, where you can find many animations by various (more or less) talented creators. Currently there's +510 animations uploaded, so I believe it's more than enough to close this haha
