### ISSUE TITLE
Size bug 

### ISSUE THREAD

**Issue by GithubUser559** [KaruzoHikari/Wii-Phone#90]
I don't know what I did, I clicked on a channel and this happened
![Screenshot_2024-04-22-17-02-27-652](https://github.com/KaruzoHikari/Revo-Launcher/assets/151972759/2a264a3c-38f4-4059-bbb8-176012f4f0e9)
![Screenshot_2024-04-22-17-02-07-734](https://github.com/KaruzoHikari/Revo-Launcher/assets/151972759/02c88ecf-c030-4c07-8c1a-e14eba582ce9)
![Screenshot_2024-04-22-17-01-50-081](https://github.com/KaruzoHikari/Revo-Launcher/assets/151972759/9563ab5d-d8c9-4cb5-9291-d127aa8f5ff0)
![Screenshot_2024-04-22-16-55-26-961](https://github.com/KaruzoHikari/Revo-Launcher/assets/151972759/8b86937d-23f0-4d96-b04c-343ab335f940)
![Screenshot_2024-04-22-17-01-39-680](https://github.com/KaruzoHikari/Revo-Launcher/assets/151972759/6ab13cf1-c66b-4782-958e-8874b23b234b)

**Comment by KaruzoHikari** [comment]
I can see that you have the debug console open, can you show me what the red error that appears is?
It'd help me a lot to learn what the issue is

**Comment by GithubUser559** [comment]
It's nothing, I read it. I just identified the problem, It happens when I click on an app just when I move to landscape mode.Changing the conversation I already made the final version of the Wii U Evolution Theme With Themes white Black Green (the main one)AND The Blue.I made the few improvements that were missing.Then reject Themes under review to send updated versions

**Comment by GithubUser559** [comment]
Someday Wii Phone will support .MP4? (Without sound) To have better quality than a gif and save more space.
