### ISSUE TITLE
Icons + Banners appear blank after restart

### ISSUE THREAD

**Issue by Ricca665** [KaruzoHikari/Wii-Phone#99]
Revo launcher (APK) worked fine for a few days, until from yesterday, when i tried to open up the apps on my launcher, the icons appeared fine, but the banners not, after restart, both of them were blank, except the default ones (Shop channel, Photo channel, Disk channel, Miis channel and yt channel plus the custom channel that i made)
![Screenshot_20240504-101010](https://github.com/KaruzoHikari/Revo-Launcher/assets/84286914/06a44123-c776-4e1b-8f41-4ed8cd118a2a)
![Screenshot_20240504-103706](https://github.com/KaruzoHikari/Revo-Launcher/assets/84286914/7bf26ff3-8bb4-477c-a3c8-290285f449fd)

**Comment by KaruzoHikari** [comment]
Hey Ricca, please try updating to v5.2.2 and setting up an animation once again, to check if it got fixed.
Thanks!

**Comment by Ricca665** [comment]
Fixed! Thank you
